<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Recruitment;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class JapaneseRecruitmentSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::firstOrCreate(
            ['email' => 'admin@example.com'],
            [
                'name' => '管理者',
                'password' => Hash::make('password'),
                'role' => 'admin',
            ]
        );

        $recruiter = User::firstOrCreate(
            ['email' => 'recruiter@example.com'],
            [
                'name' => '採用担当者',
                'password' => Hash::make('password'),
                'role' => 'recruiter',
            ]
        );

        $recruitments = [
            [
                'title' => 'シニアフルスタックエンジニア',
                'company_name' => '株式会社テックイノベーション',
                'location' => '東京都渋谷区',
                'employment_type' => 'full-time',
                'salary_min' => 8000000,
                'salary_max' => 12000000,
                'salary_currency' => 'JPY',
                'description' => '最新技術を活用したWebアプリケーション開発をリードしていただきます。アジャイル開発環境で、チームと協力しながらプロダクトの成長に貢献できる方を募集しています。',
                'requirements' => 'React/Vue.jsでの開発経験3年以上、Node.js/Python/Goいずれかのバックエンド経験、AWSまたはGCPの実務経験',
                'responsibilities' => 'フロントエンド・バックエンドの設計・開発、コードレビュー、技術選定、ジュニアメンバーの育成',
                'benefits' => 'フレックスタイム制、リモートワーク可、書籍購入補助、資格取得支援、健康診断',
                'application_deadline' => now()->addDays(30),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'Webデザイナー',
                'company_name' => '株式会社クリエイティブラボ',
                'location' => '東京都港区',
                'employment_type' => 'full-time',
                'salary_min' => 4500000,
                'salary_max' => 6500000,
                'salary_currency' => 'JPY',
                'description' => 'BtoB向けWebサービスのUI/UXデザインを担当していただきます。ユーザーリサーチからプロトタイプ作成まで幅広くお任せします。',
                'requirements' => 'Figmaの実務経験2年以上、HTML/CSSの基本知識、ポートフォリオ提出必須',
                'responsibilities' => 'UIデザイン、プロトタイプ作成、デザインシステムの構築・運用、エンジニアとの連携',
                'benefits' => '完全週休2日制、年間休日125日、産休・育休実績あり、副業OK',
                'application_deadline' => now()->addDays(20),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'インフラエンジニア',
                'company_name' => '合同会社クラウドソリューションズ',
                'location' => '大阪府大阪市北区',
                'employment_type' => 'full-time',
                'salary_min' => 6000000,
                'salary_max' => 9000000,
                'salary_currency' => 'JPY',
                'description' => 'クラウドインフラの設計・構築・運用をお任せします。AWS/GCPを中心としたマルチクラウド環境での経験を活かせます。',
                'requirements' => 'AWS認定資格保有者優遇、Terraform/Ansibleの経験、Linux運用経験3年以上',
                'responsibilities' => 'インフラ設計・構築、CI/CDパイプライン構築、監視・アラート設計、セキュリティ対策',
                'benefits' => '資格手当、リモートワーク、技術カンファレンス参加費補助',
                'application_deadline' => now()->addDays(25),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'モバイルアプリエンジニア（iOS）',
                'company_name' => '株式会社アプリファクトリー',
                'location' => '東京都新宿区',
                'employment_type' => 'full-time',
                'salary_min' => 5500000,
                'salary_max' => 8000000,
                'salary_currency' => 'JPY',
                'description' => '自社サービスのiOSアプリ開発を担当していただきます。Swift/SwiftUIを使った最新の開発手法で、ユーザー体験を向上させましょう。',
                'requirements' => 'Swift開発経験2年以上、App Store公開経験、SwiftUIの知識',
                'responsibilities' => 'iOSアプリの設計・開発・リリース、パフォーマンス改善、プッシュ通知実装',
                'benefits' => '最新Mac支給、WWDC参加支援、フレックスタイム制',
                'application_deadline' => now()->addDays(15),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'データサイエンティスト',
                'company_name' => '株式会社AIリサーチ',
                'location' => '東京都千代田区',
                'employment_type' => 'full-time',
                'salary_min' => 7000000,
                'salary_max' => 11000000,
                'salary_currency' => 'JPY',
                'description' => '機械学習モデルの開発・運用を担当していただきます。大規模データを活用した予測モデルの構築に携わることができます。',
                'requirements' => 'Python/Rでのデータ分析経験3年以上、統計学の知識、機械学習フレームワーク（TensorFlow/PyTorch）の経験',
                'responsibilities' => 'データ分析、機械学習モデル開発、A/Bテスト設計、分析レポート作成',
                'benefits' => '研究開発費補助、学会参加支援、フルリモート可',
                'application_deadline' => now()->addDays(35),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'プロジェクトマネージャー',
                'company_name' => '株式会社システムインテグレーション',
                'location' => '神奈川県横浜市',
                'employment_type' => 'full-time',
                'salary_min' => 7500000,
                'salary_max' => 10000000,
                'salary_currency' => 'JPY',
                'description' => '大規模システム開発プロジェクトのマネジメントをお任せします。顧客折衝からチーム管理まで幅広く活躍いただけます。',
                'requirements' => 'PM経験5年以上、PMP資格保有者優遇、ウォーターフォール/アジャイル両方の経験',
                'responsibilities' => 'プロジェクト計画・進捗管理、顧客対応、リスク管理、チームビルディング',
                'benefits' => 'マネジメント手当、出張手当、家族手当',
                'application_deadline' => now()->addDays(40),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'QAエンジニア',
                'company_name' => '株式会社品質保証パートナーズ',
                'location' => '東京都品川区',
                'employment_type' => 'full-time',
                'salary_min' => 4500000,
                'salary_max' => 7000000,
                'salary_currency' => 'JPY',
                'description' => 'Webアプリケーションの品質保証業務を担当していただきます。テスト自動化の推進にも携わることができます。',
                'requirements' => 'テスト設計経験2年以上、Selenium/Cypressの経験あれば尚可、JSTQB資格保有者優遇',
                'responsibilities' => 'テスト計画・設計・実行、テスト自動化、品質レポート作成、開発チームとの連携',
                'benefits' => '資格取得支援、勉強会参加費補助、残業少なめ',
                'application_deadline' => now()->addDays(20),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'バックエンドエンジニア（Go）',
                'company_name' => '株式会社フィンテックイノベーション',
                'location' => '東京都中央区',
                'employment_type' => 'full-time',
                'salary_min' => 6500000,
                'salary_max' => 10000000,
                'salary_currency' => 'JPY',
                'description' => '金融系サービスのバックエンド開発を担当していただきます。高可用性・高セキュリティが求められる環境での開発経験を積むことができます。',
                'requirements' => 'Go言語での開発経験2年以上、マイクロサービスアーキテクチャの経験、gRPC/REST APIの設計経験',
                'responsibilities' => 'バックエンドAPI開発、データベース設計、パフォーマンスチューニング、セキュリティ対策',
                'benefits' => 'ストックオプション、書籍購入補助無制限、健康増進手当',
                'application_deadline' => now()->addDays(30),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'SREエンジニア',
                'company_name' => '株式会社メガプラットフォーム',
                'location' => '東京都目黒区',
                'employment_type' => 'full-time',
                'salary_min' => 7000000,
                'salary_max' => 12000000,
                'salary_currency' => 'JPY',
                'description' => '大規模サービスの信頼性向上に取り組んでいただきます。SLO/SLIの設計からインシデント対応まで幅広く担当できます。',
                'requirements' => 'SRE/インフラ経験3年以上、Kubernetes運用経験、Prometheus/Grafanaの経験',
                'responsibilities' => 'システム監視・アラート設計、障害対応・ポストモーテム、自動化推進、キャパシティプランニング',
                'benefits' => 'オンコール手当、最新機器支給、カンファレンス登壇支援',
                'application_deadline' => now()->addDays(25),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'Androidエンジニア',
                'company_name' => '株式会社モバイルテック',
                'location' => '福岡県福岡市',
                'employment_type' => 'full-time',
                'salary_min' => 5000000,
                'salary_max' => 7500000,
                'salary_currency' => 'JPY',
                'description' => 'ヘルスケアアプリのAndroid開発を担当していただきます。Kotlin/Jetpack Composeを使ったモダンな開発環境です。',
                'requirements' => 'Kotlin開発経験2年以上、Google Play公開経験、MVVM/Clean Architectureの理解',
                'responsibilities' => 'Androidアプリ開発、Jetpack Compose導入、CI/CD構築、コードレビュー',
                'benefits' => 'フルリモート可、福岡オフィス勤務可、技術書籍購入補助',
                'application_deadline' => now()->addDays(20),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'セキュリティエンジニア',
                'company_name' => '株式会社サイバーセキュリティ',
                'location' => '東京都文京区',
                'employment_type' => 'full-time',
                'salary_min' => 7000000,
                'salary_max' => 11000000,
                'salary_currency' => 'JPY',
                'description' => '企業向けセキュリティサービスの開発・運用を担当していただきます。脆弱性診断やペネトレーションテストの経験を活かせます。',
                'requirements' => 'セキュリティ関連業務3年以上、CISSP/CEH資格保有者優遇、Webアプリケーションセキュリティの知識',
                'responsibilities' => '脆弱性診断、セキュリティ監査、インシデント対応、セキュリティ教育',
                'benefits' => '資格取得全額補助、セキュリティカンファレンス参加支援、高セキュリティ環境',
                'application_deadline' => now()->addDays(35),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'テックリード',
                'company_name' => '株式会社スタートアップベンチャー',
                'location' => '東京都渋谷区',
                'employment_type' => 'full-time',
                'salary_min' => 9000000,
                'salary_max' => 14000000,
                'salary_currency' => 'JPY',
                'description' => '急成長中のスタートアップで技術チームをリードしていただきます。アーキテクチャ設計から採用まで幅広くお任せします。',
                'requirements' => 'エンジニア経験7年以上、リーダー/マネジメント経験3年以上、技術選定の経験',
                'responsibilities' => '技術戦略策定、アーキテクチャ設計、チームマネジメント、エンジニア採用',
                'benefits' => 'ストックオプション、経営会議参加、裁量労働制',
                'application_deadline' => now()->addDays(45),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'フロントエンドエンジニア（React）',
                'company_name' => '株式会社ECプラットフォーム',
                'location' => '東京都豊島区',
                'employment_type' => 'full-time',
                'salary_min' => 5000000,
                'salary_max' => 7500000,
                'salary_currency' => 'JPY',
                'description' => 'ECサイトのフロントエンド開発を担当していただきます。React/Next.jsを使った高速なUI開発に携わることができます。',
                'requirements' => 'React開発経験2年以上、TypeScriptの実務経験、パフォーマンス最適化の知識',
                'responsibilities' => 'フロントエンド開発、コンポーネント設計、パフォーマンス改善、A/Bテスト実装',
                'benefits' => '社員割引、フレックスタイム、週2リモート可',
                'application_deadline' => now()->addDays(20),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'PHPエンジニア（Laravel）',
                'company_name' => '株式会社Webサービス開発',
                'location' => '愛知県名古屋市',
                'employment_type' => 'full-time',
                'salary_min' => 4500000,
                'salary_max' => 6500000,
                'salary_currency' => 'JPY',
                'description' => 'Laravelを使用したWebアプリケーション開発を担当していただきます。自社サービスの新機能開発に携わることができます。',
                'requirements' => 'PHP開発経験2年以上、Laravel経験1年以上、MySQL/PostgreSQLの経験',
                'responsibilities' => 'Webアプリケーション開発、API設計・実装、データベース設計、テスト作成',
                'benefits' => '名古屋駅直結オフィス、残業月20時間以下、有給取得率80%以上',
                'application_deadline' => now()->addDays(25),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'ITコンサルタント',
                'company_name' => '株式会社戦略コンサルティング',
                'location' => '東京都千代田区',
                'employment_type' => 'full-time',
                'salary_min' => 8000000,
                'salary_max' => 15000000,
                'salary_currency' => 'JPY',
                'description' => '大手企業のDX推進プロジェクトに参画していただきます。戦略立案から実行支援まで一貫して関わることができます。',
                'requirements' => 'コンサルティング経験3年以上、IT/デジタル領域の知識、ビジネスレベルの英語力',
                'responsibilities' => 'DX戦略策定、業務プロセス改善、システム導入支援、クライアント折衝',
                'benefits' => '高額年収、グローバル案件あり、MBA取得支援',
                'application_deadline' => now()->addDays(30),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'カスタマーサクセスエンジニア',
                'company_name' => '株式会社SaaSソリューション',
                'location' => '東京都港区',
                'employment_type' => 'full-time',
                'salary_min' => 5000000,
                'salary_max' => 7000000,
                'salary_currency' => 'JPY',
                'description' => 'SaaSプロダクトの導入支援・技術サポートを担当していただきます。顧客の課題解決に技術力で貢献できます。',
                'requirements' => 'エンジニア経験2年以上、顧客対応経験、APIの基本知識',
                'responsibilities' => '導入支援、技術サポート、顧客要望のフィードバック、ドキュメント作成',
                'benefits' => 'インセンティブ制度、顧客満足度ボーナス、研修制度充実',
                'application_deadline' => now()->addDays(15),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'ゲームエンジニア（Unity）',
                'company_name' => '株式会社ゲームスタジオ',
                'location' => '東京都渋谷区',
                'employment_type' => 'full-time',
                'salary_min' => 5000000,
                'salary_max' => 8000000,
                'salary_currency' => 'JPY',
                'description' => 'スマートフォン向けゲームの開発を担当していただきます。Unity/C#を使った開発経験を活かせます。',
                'requirements' => 'Unity開発経験2年以上、C#の実務経験、ゲームタイトルのリリース経験',
                'responsibilities' => 'ゲームクライアント開発、パフォーマンス最適化、新機能実装、バグ修正',
                'benefits' => 'ゲーム購入補助、最新ゲーム機支給、フレックスタイム',
                'application_deadline' => now()->addDays(30),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'DevOpsエンジニア',
                'company_name' => '株式会社クラウドネイティブ',
                'location' => '東京都港区',
                'employment_type' => 'full-time',
                'salary_min' => 6000000,
                'salary_max' => 9000000,
                'salary_currency' => 'JPY',
                'description' => 'CI/CDパイプラインの構築・運用を担当していただきます。開発チームの生産性向上に貢献できます。',
                'requirements' => 'DevOps経験2年以上、Jenkins/GitHub Actions/GitLab CIの経験、Docker/Kubernetesの経験',
                'responsibilities' => 'CI/CD構築、インフラ自動化、開発環境整備、デプロイ改善',
                'benefits' => 'リモートワーク、技術カンファレンス参加費補助、資格手当',
                'application_deadline' => now()->addDays(25),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'MLエンジニア',
                'company_name' => '株式会社ディープラーニング研究所',
                'location' => '東京都文京区',
                'employment_type' => 'full-time',
                'salary_min' => 8000000,
                'salary_max' => 13000000,
                'salary_currency' => 'JPY',
                'description' => '機械学習モデルの本番環境への導入・運用を担当していただきます。研究成果をプロダクトに活かす架け橋となる役割です。',
                'requirements' => 'Python開発経験3年以上、機械学習モデルのデプロイ経験、MLOpsの知識',
                'responsibilities' => 'MLパイプライン構築、モデルデプロイ・監視、A/Bテスト、性能改善',
                'benefits' => 'GPU環境完備、論文発表支援、博士号取得支援',
                'application_deadline' => now()->addDays(35),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'Webエンジニア（新卒）',
                'company_name' => '株式会社ITソリューションズ',
                'location' => '東京都新宿区',
                'employment_type' => 'full-time',
                'salary_min' => 3500000,
                'salary_max' => 4500000,
                'salary_currency' => 'JPY',
                'description' => '2025年新卒採用！未経験からWebエンジニアを目指す方を募集しています。充実した研修制度で成長をサポートします。',
                'requirements' => '2025年3月卒業見込み、プログラミングへの興味、基本的なPCスキル',
                'responsibilities' => 'Webアプリケーション開発（研修後）、テスト・運用、ドキュメント作成',
                'benefits' => '3ヶ月研修、メンター制度、資格取得支援、住宅手当',
                'application_deadline' => now()->addDays(60),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'データベースエンジニア',
                'company_name' => '株式会社データマネジメント',
                'location' => '大阪府大阪市中央区',
                'employment_type' => 'full-time',
                'salary_min' => 5500000,
                'salary_max' => 8000000,
                'salary_currency' => 'JPY',
                'description' => '大規模データベースの設計・運用を担当していただきます。PostgreSQL/MySQLの専門知識を活かせます。',
                'requirements' => 'DBA経験3年以上、PostgreSQL/MySQLのチューニング経験、バックアップ・リカバリの知識',
                'responsibilities' => 'DB設計・構築、パフォーマンスチューニング、障害対応、移行支援',
                'benefits' => '大阪駅直結、残業少なめ、有給消化率90%',
                'application_deadline' => now()->addDays(30),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'テクニカルライター',
                'company_name' => '株式会社ドキュメントプロ',
                'location' => '東京都千代田区',
                'employment_type' => 'contract',
                'salary_min' => 4000000,
                'salary_max' => 6000000,
                'salary_currency' => 'JPY',
                'description' => '技術文書・マニュアルの作成を担当していただきます。複雑な技術を分かりやすく伝える力を発揮できます。',
                'requirements' => 'テクニカルライティング経験2年以上、IT/ソフトウェアの基礎知識、日本語ネイティブレベル',
                'responsibilities' => 'API仕様書作成、ユーザーマニュアル作成、ヘルプドキュメント整備、翻訳レビュー',
                'benefits' => 'フルリモート可、フレックス、スキルアップ研修',
                'application_deadline' => now()->addDays(20),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'Webマーケティングエンジニア',
                'company_name' => '株式会社デジタルマーケティング',
                'location' => '東京都中央区',
                'employment_type' => 'full-time',
                'salary_min' => 5000000,
                'salary_max' => 7500000,
                'salary_currency' => 'JPY',
                'description' => 'マーケティング施策の技術的な実装を担当していただきます。Google Analytics、広告タグ、LP制作などの経験を活かせます。',
                'requirements' => 'HTML/CSS/JavaScriptの実務経験、GA4/GTMの設定経験、SEOの基礎知識',
                'responsibilities' => 'タグ実装、LP制作、A/Bテスト実装、レポート自動化',
                'benefits' => 'マーケティング予算の知見が得られる、副業OK、フレックス',
                'application_deadline' => now()->addDays(25),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'VRエンジニア',
                'company_name' => '株式会社XRテクノロジー',
                'location' => '東京都港区',
                'employment_type' => 'full-time',
                'salary_min' => 6000000,
                'salary_max' => 9000000,
                'salary_currency' => 'JPY',
                'description' => 'VR/ARアプリケーションの開発を担当していただきます。Unity/Unreal Engineを使った没入型体験の開発に携わることができます。',
                'requirements' => 'Unity/Unreal Engine経験2年以上、VR開発経験、3Dグラフィックスの知識',
                'responsibilities' => 'VRアプリ開発、3Dインタラクション設計、パフォーマンス最適化、プロトタイプ作成',
                'benefits' => 'VR機器支給、最先端技術に触れられる、グローバルプロジェクト参加機会',
                'application_deadline' => now()->addDays(30),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'Rubyエンジニア',
                'company_name' => '株式会社レールズプロジェクト',
                'location' => '京都府京都市',
                'employment_type' => 'full-time',
                'salary_min' => 5000000,
                'salary_max' => 7500000,
                'salary_currency' => 'JPY',
                'description' => 'Ruby on Railsを使用したWebサービス開発を担当していただきます。京都の落ち着いた環境で開発に集中できます。',
                'requirements' => 'Ruby/Rails開発経験2年以上、RSpecでのテスト経験、GitHubでの開発経験',
                'responsibilities' => 'Rails開発、API設計・実装、テスト作成、コードレビュー',
                'benefits' => '京都駅近くのモダンオフィス、観光シーズンの特別休暇、リモート併用可',
                'application_deadline' => now()->addDays(25),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'ブロックチェーンエンジニア',
                'company_name' => '株式会社Web3ラボ',
                'location' => '東京都渋谷区',
                'employment_type' => 'full-time',
                'salary_min' => 8000000,
                'salary_max' => 15000000,
                'salary_currency' => 'JPY',
                'description' => 'ブロックチェーン技術を活用したサービス開発を担当していただきます。Web3の最前線で活躍できます。',
                'requirements' => 'Solidity開発経験、スマートコントラクトの知識、Web3.js/ethers.jsの経験',
                'responsibilities' => 'スマートコントラクト開発、DApp開発、セキュリティ監査対応、技術調査',
                'benefits' => '暗号資産報酬あり、グローバルカンファレンス参加支援、フルリモート可',
                'application_deadline' => now()->addDays(40),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'アルバイト - テスター',
                'company_name' => '株式会社ゲームQA',
                'location' => '東京都新宿区',
                'employment_type' => 'part-time',
                'salary_min' => 1200,
                'salary_max' => 1500,
                'salary_currency' => 'JPY',
                'description' => 'ゲームのテストプレイ・バグ報告を担当していただきます。ゲーム好きな方大歓迎！週3日〜OK。',
                'requirements' => 'ゲームが好きな方、細かい作業が得意な方、PCの基本操作ができる方',
                'responsibilities' => 'ゲームプレイ、バグ報告、テストケース実行、レポート作成',
                'benefits' => 'ゲームを先行プレイできる、シフト自由、交通費支給',
                'application_deadline' => now()->addDays(14),
                'status' => 'published',
                'created_by' => $admin->id,
                'published_at' => now(),
            ],
            [
                'title' => 'インターン - エンジニア',
                'company_name' => '株式会社テックスタートアップ',
                'location' => '東京都渋谷区',
                'employment_type' => 'internship',
                'salary_min' => 1500,
                'salary_max' => 2000,
                'salary_currency' => 'JPY',
                'description' => '長期インターン募集！実際のプロダクト開発に携わりながら、実践的なスキルを身につけることができます。',
                'requirements' => '大学生・大学院生、プログラミング学習経験（言語不問）、週2日以上勤務可能',
                'responsibilities' => '機能開発、テスト作成、コードレビュー参加、技術調査',
                'benefits' => 'メンター制度、技術勉強会参加、正社員登用あり',
                'application_deadline' => now()->addDays(30),
                'status' => 'published',
                'created_by' => $recruiter->id,
                'published_at' => now(),
            ],
            [
                'title' => 'CTO候補',
                'company_name' => '株式会社ネクストユニコーン',
                'location' => '東京都港区',
                'employment_type' => 'full-time',
                'salary_min' => 15000000,
                'salary_max' => 25000000,
                'salary_currency' => 'JPY',
                'description' => 'シリーズAを調達したスタートアップで、CTOとして技術組織を牽引していただきます。経営にも参画できるポジションです。',
                'requirements' => 'エンジニア経験10年以上、CTO/VPoE経験、組織マネジメント経験、事業戦略への関与経験',
                'responsibilities' => '技術戦略策定、エンジニア組織構築、採用、経営会議参加、投資家対応',
                'benefits' => 'ストックオプション（大型）、役員待遇、完全裁量労働',
                'application_deadline' => now()->addDays(60),
                'status' => 'draft',
                'created_by' => $admin->id,
            ],
            [
                'title' => 'クラウドアーキテクト',
                'company_name' => '株式会社エンタープライズクラウド',
                'location' => '東京都千代田区',
                'employment_type' => 'full-time',
                'salary_min' => 10000000,
                'salary_max' => 15000000,
                'salary_currency' => 'JPY',
                'description' => '大規模クラウドインフラの設計・構築を担当していただきます。マルチクラウド環境でのアーキテクチャ設計経験を活かせます。',
                'requirements' => 'AWS/Azure/GCP認定資格、アーキテクト経験5年以上、大規模システム設計経験',
                'responsibilities' => 'アーキテクチャ設計、技術選定、ベンダー折衝、チーム育成',
                'benefits' => '技術顧問ポジションへの道、グローバル案件、高額年収',
                'application_deadline' => now()->addDays(45),
                'status' => 'closed',
                'created_by' => $recruiter->id,
                'published_at' => now()->subDays(10),
            ],
        ];

        foreach ($recruitments as $recruitmentData) {
            Recruitment::firstOrCreate(
                [
                    'title' => $recruitmentData['title'],
                    'company_name' => $recruitmentData['company_name'],
                ],
                $recruitmentData
            );
        }
    }
}
